name: "Setup"
inputs:
  java-version:
    default: 17
  konan:
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Check out
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Set up JDK Temurin ${{ inputs.java-version }}
      uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
      with:
        distribution: temurin
        java-version: ${{ inputs.java-version }}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
    - name: Cached Konan
      if: ${{ inputs.konan == 'true' }}
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: ~/.konan
        key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-konan-
