name: "Check with Android"
inputs:
  gradle-task:
    description: "Which Gradle convention to use: 'AGP' (./gradlew connectedCheck) or 'KMP' (./gradlew androidConnectedCheck)."
    required: false
    default: "KMP"
runs:
  using: "composite"
  steps:
    - name: Check
      run: ./gradlew check
      shell: bash
    - name: Enable KVM group perms
      shell: bash
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
    - name: Instrumentation tests
      uses: reactivecircus/android-emulator-runner@e89f39f1abbbd05b1113a29cf4db69e7540cae5a # v2.37.0
      with:
        api-level: 35
        arch: x86_64
        ndk: 25.2.9519653
        cmake: 3.10.2.4988404
        script: ./gradlew ${{ inputs.gradle-task == 'AGP' && 'connectedCheck' || 'androidConnectedCheck' }}
