name: "Instrumentation tests on Android"
runs:
  using: "composite"
  runs-on: ubuntu-latest
  timeout-minutes: 60
  strategy:
      fail-fast: true
  steps:
    - name: Check
      run: ./gradlew check
      shell: bash
    - name: Instrumentation tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 35
        ndk: 25.2.9519653
        cmake: 3.10.2.4988404
        script: ./gradlew connectedCheck
