name: "Check with Android"
runs:
  using: "composite"
  steps:
    - name: Check
        run: ./gradlew check
        shell: bash
    - name: Check Android
        uses: reactivecircus/android-emulator-runner@d94c3fbe4fe6a29e4a5ba47c12fb47677c73656b #v2.28.0
        with:
          api-level: 29
          ndk: 21.3.6528147
          cmake: 3.10.2.4988404
          script: ./gradlew connectedCheck
