on:
  workflow_call:
    secrets:
      SONATYPE_USERNAME:
        required: true
      SONATYPE_PASSWORD:
        required: true
      SONATYPE_PROFILE_ID:
        required: true
    outputs:
      repository-id:
        description: "Staging repository ID created on Nexus."
        value: ${{ jobs.create-staging-repository.outputs.repository-id }}

jobs:
  create-staging-repository:
    name: Create Nexus staging repository
    runs-on: ubuntu-latest
    outputs:
      repository-id: ${{ steps.create.outputs.repository_id }}
    steps:
      - id: create
        uses: nexus-actions/create-nexus-staging-repo@v1
        with:
          base_url: https://s01.oss.sonatype.org/service/local/
          username: ${{ secrets.SONATYPE_USERNAME }}
          password: ${{ secrets.SONATYPE_PASSWORD }}
          staging_profile_id: ${{ secrets.SONATYPE_PROFILE_ID }}
          description: ${{ github.repository }}/${{ github.workflow }}#${{ github.run_number }}
