on:
  workflow_call:
    inputs:
      repository-id:
        required: true
        type: string
      build-upload-result:
        required: true
        type: string
    secrets:
      SONATYPE_TOKEN_USER:
        required: true
      SONATYPE_TOKEN_PASSWORD:
        required: true

jobs:
  complete-staging-repository:
    name: Complete Nexus staging repository
    runs-on: ubuntu-latest
    steps:
      - name: Discard
        if: ${{ inputs.build-upload-result != 'success' }}
        uses: nexus-actions/drop-nexus-staging-repo@v1
        with:
          base_url: https://ossrh-staging-api.central.sonatype.com/service/local/
          username: ${{ secrets.SONATYPE_TOKEN_USER }}
          password: ${{ secrets.SONATYPE_TOKEN_PASSWORD }}
          staging_repository_id: ${{ inputs.repository-id }}
      - name: Release
        if: ${{ inputs.build-upload-result == 'success' }}
        uses: nexus-actions/release-nexus-staging-repo@v1
        with:
          base_url: https://ossrh-staging-api.central.sonatype.com/service/local/
          username: ${{ secrets.SONATYPE_TOKEN_USER }}
          password: ${{ secrets.SONATYPE_TOKEN_PASSWORD }}
          staging_repository_id: ${{ inputs.repository-id }}
