on: workflow_call

jobs:
  unit-tests:
    name: Unit tests
    runs-on: macOS-latest
    steps:
      - name: Setup
        uses: kosi-libs/kodein-internal-github-actions/setup@main
      - name: Check
        run: ./gradlew check
        shell: bash